version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: screenshot-saas-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: screenshot-saas
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - screenshot-saas-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: screenshot-saas-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/screenshot-saas?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      UPLOAD_DIR: ./uploads
      MAX_FILE_SIZE: 10485760
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      SCREENSHOT_TIMEOUT: 30000
      CRAWL_MAX_DEPTH: 2
      CRAWL_MAX_PAGES: 50
      ADMIN_EMAIL: admin@screenshot-saas.com
      ADMIN_PASSWORD: admin123
      DEFAULT_SCREENSHOTS_PER_MONTH: 100
      DEFAULT_MAX_PROJECTS: 10
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - screenshot-saas-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: screenshot-saas-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_WS_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - screenshot-saas-network

volumes:
  mongodb_data:
    driver: local

networks:
  screenshot-saas-network:
    driver: bridge
